npx @svgr/cli --icon 16px --ext jsx -d ./jsx ./svg/Add.svg
npx @svgr/cli --icon 16px --ext jsx -d ./jsx ./svg/ArrowClockwise.svg
npx @svgr/cli --icon 16px --ext jsx -d ./jsx ./svg/ArrowDown.svg
npx @svgr/cli --icon 16px --ext jsx -d ./jsx ./svg/ArrowLeft.svg
npx @svgr/cli --icon 16px --ext jsx -d ./jsx ./svg/ArrowRight.svg
npx @svgr/cli --icon 16px --ext jsx -d ./jsx ./svg/ArrowUp.svg
npx @svgr/cli --icon 16px --ext jsx -d ./jsx ./svg/ArrowUpLeft.svg
npx @svgr/cli --icon 16px --ext jsx -d ./jsx ./svg/Briefcase.svg
npx @svgr/cli --icon 16px --ext jsx -d ./jsx ./svg/Check.svg
npx @svgr/cli --icon 16px --ext jsx -d ./jsx ./svg/Clock.svg
npx @svgr/cli --icon 16px --ext jsx -d ./jsx ./svg/Close.svg
npx @svgr/cli --icon 16px --ext jsx -d ./jsx ./svg/CloseRounded.svg
npx @svgr/cli --icon 16px --ext jsx -d ./jsx ./svg/Column.svg
npx @svgr/cli --icon 16px --ext jsx -d ./jsx ./svg/Compass.svg
npx @svgr/cli --icon 16px --ext jsx -d ./jsx ./svg/CopySimple.svg
npx @svgr/cli --icon 16px --ext jsx -d ./jsx ./svg/Cycle.svg
npx @svgr/cli --icon 16px --ext jsx -d ./jsx ./svg/Download.svg
npx @svgr/cli --icon 16px --ext jsx -d ./jsx ./svg/EditPen.svg
npx @svgr/cli --icon 16px --ext jsx -d ./jsx ./svg/EditSquare.svg
npx @svgr/cli --icon 16px --ext jsx -d ./jsx ./svg/File.svg
npx @svgr/cli --icon 16px --ext jsx -d ./jsx ./svg/Finder.svg
npx @svgr/cli --icon 16px --ext jsx -d ./jsx ./svg/FolderOpen.svg
npx @svgr/cli --icon 16px --ext jsx -d ./jsx ./svg/Gallery.svg
npx @svgr/cli --icon 16px --ext jsx -d ./jsx ./svg/Gear.svg
npx @svgr/cli --icon 16px --ext jsx -d ./jsx ./svg/Grid.svg
npx @svgr/cli --icon 16px --ext jsx -d ./jsx ./svg/Image.svg
npx @svgr/cli --icon 16px --ext jsx -d ./jsx ./svg/List.svg
npx @svgr/cli --icon 16px --ext jsx -d ./jsx ./svg/Loading.svg
npx @svgr/cli --icon 16px --ext jsx -d ./jsx ./svg/MagnifyingGlass.svg
npx @svgr/cli --icon 16px --ext jsx -d ./jsx ./svg/Mic.svg
npx @svgr/cli --icon 16px --ext jsx -d ./jsx ./svg/Minus.svg
npx @svgr/cli --icon 16px --ext jsx -d ./jsx ./svg/MoreHorizontal.svg
npx @svgr/cli --icon 16px --ext jsx -d ./jsx ./svg/MoreVertical.svg
npx @svgr/cli --icon 16px --ext jsx -d ./jsx ./svg/Play.svg
npx @svgr/cli --icon 16px --ext jsx -d ./jsx ./svg/QuestionMark.svg
npx @svgr/cli --icon 16px --ext jsx -d ./jsx ./svg/RemoveFromList.svg
npx @svgr/cli --icon 16px --ext jsx -d ./jsx ./svg/RemoveSquare.svg
npx @svgr/cli --icon 16px --ext jsx -d ./jsx ./svg/Rocket.svg
npx @svgr/cli --icon 16px --ext jsx -d ./jsx ./svg/ScreenExpand.svg
npx @svgr/cli --icon 16px --ext jsx -d ./jsx ./svg/ScreenNarrow.svg
npx @svgr/cli --icon 16px --ext jsx -d ./jsx ./svg/SkipBack.svg
npx @svgr/cli --icon 16px --ext jsx -d ./jsx ./svg/SkipForward.svg
npx @svgr/cli --icon 16px --ext jsx -d ./jsx ./svg/SpeakerHigh.svg
npx @svgr/cli --icon 16px --ext jsx -d ./jsx ./svg/SpeakerSimpleX.svg
npx @svgr/cli --icon 16px --ext jsx -d ./jsx ./svg/Tag.svg
npx @svgr/cli --icon 16px --ext jsx -d ./jsx ./svg/Trash.svg
npx @svgr/cli --icon 16px --ext jsx -d ./jsx ./svg/UpAndDownArrow.svg
npx @svgr/cli --icon 16px --ext jsx -d ./jsx ./svg/Upload.svg
