-- CreateTable
CREATE TABLE `VideoTask` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `videoPath` VARCHAR(500) NOT NULL,
    `videoFileHash` VARCHAR(64) NOT NULL,
    `taskType` ENUM('FRAMES', 'FRAME_CONTENT_EMBEDDING', 'AUDIO', 'TRANSCRIPT', 'TRANSCRIPT_EMBEDDING') NOT NULL,
    `startsAt` DATETIME(3) NULL,
    `endsAt` DATETIME(3) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
