[package]
name = "storage-macro"
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { workspace = true }
quote = { workspace = true }
storage = { path = "../storage" }
global-variable = { path = "../global-variable" }
async-trait = { workspace = true }
