/*
 * This file was automatically generated by a script.
 * To regenerate this file, run: pnpm assets gen
 */

import Document_Light from "./Document_Light.png";
import Folder_Light from "./Folder_Light.png";

export {
	Document_Light,
	Folder_Light,
};
