// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "files", input: string | null, result: any } | 
        { key: "folders", input: never, result: any } | 
        { key: "ls", input: string, result: any } | 
        { key: "users", input: never, result: any } | 
        { key: "version", input: never, result: string },
    mutations: never,
    subscriptions: never
};
