/*
 * This file was automatically generated by a script.
 * To regenerate this file, run: pnpm assets gen
 */

import Document_Light from "./Document_Light.png";
import Folder_Light from "./Folder_Light.png";
import Drop_To_Folder from "./Drop_To_Folder.png";
import Video_Files from "./Video_Files.png";
import Video_File from "./Video_File.png";

export {
  Document_Light,
  Folder_Light,
  Drop_To_Folder,
  Video_Files,
  Video_File,
};
