// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "files.home_dir", input: never, result: string } | 
        { key: "files.ls", input: string, result: any } | 
        { key: "libraries.list", input: never, result: any } | 
        { key: "users.list", input: never, result: any } | 
        { key: "version", input: never, result: string } | 
        { key: "video.search.all", input: string, result: SearchResultPayload[] } | 
        { key: "video.tasks.list", input: never, result: VideoTaskResult[] },
    mutations: 
        { key: "files.reveal", input: string, result: null } | 
        { key: "libraries.create", input: string, result: any } | 
        { key: "video.tasks.create", input: string, result: any },
    subscriptions: never
};

export type SearchResultPayload = { imagePath: string; videoPath: string; startTime: number }

export type VideoTaskResult = { id: number; videoPath: string; videoFileHash: string; taskType: string; startsAt: string | null; endsAt: string | null }
